### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by codepodu** [chantastic/react-svg-spinner#5]
Hi,

Thank you so much for this library! It's exactly what I wanted. 

The link to the docs: `https://chantastic.org/react-svg-spinner` worked about a week ago, but 404's as of today. While I'm sure it would be brought up soon, what do you think of having a version of docs in the Readme.md of the repo itself? 

While it may not have interactive examples, at least the API reference would be available.

**Comment by chantastic** [comment]
thanks so much for letting me know!
and thanks for using the library.

last week I moved my personal site away from Github Pages
and it broke all my project links.

i've added a redirect.
so the same URL should take you to the project page.

thanks again!
