### ISSUE TITLE
use in Browser version does not work.

### ISSUE THREAD

**Issue by joe-oli** [chantastic/react-svg-spinner#6]
as per instructions on the Readme.md "Use in the Browser" as soon as i place
<script src="https://unpkg.com/react-svg-spinner@1.0.1"></script>
in my index.html, the error in the console is:
**Uncaught ReferenceError: require is not defined**
and i cannot progress further

The versions i am using are
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.4.2/umd/react.production.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.4.2/umd/react-dom.production.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.min.js"></script>

and obviously i am placing the spinner reference as a 4th script tag below the above 3.

**Comment by chantastic** [comment]
sorry for the trouble updating the docs now.

this is the path you want: https://unpkg.com/react-svg-spinner@1.0.1/dist/index.umd.js
