### ISSUE TITLE
ReferenceError: Can't find variable: h

### ISSUE THREAD

**Issue by flodaq** [chantastic/react-svg-spinner#7]
Since the latest update (1.0.3), I am not able to use the plugin with the following error:
`ReferenceError: Can't find variable: h`

<img width="1114" alt="capture d ecran 2019-02-25 a 19 59 00" src="https://user-images.githubusercontent.com/23718178/53361359-e0dbda80-3937-11e9-8b02-809630cf9186.png">

Everything was working in previous version (1.0.1).

Any idea why it would happen?

**Comment by chantastic** [comment]
omygosh. I'm so sorry.

I just fixed this and pushed a reales: 1.0.4

I added a `prepublish` script, so I didn't have to keep building manually.
But I'm a dummy and didn't use the `--jsx React.createElement` flag for
that script.

Sorry for the inconvenience.
The new build is using `React.createElement` as it should.

**Comment by flodaq** [comment]
Working great with 1.0.4! Thanks ;)
