### ISSUE TITLE
Consider adding a license?

### ISSUE THREAD

**Issue by mxmtsk** [chantastic/react-svg-spinner#8]
Hi, thanks for the spinner. Love the simplicity and straightforward approach.

Would you mind adding a license to this repo (e.g. MIT)? I have some projects and clients where we can only use dependencies where the license is clear and I think this is helpful for everyone using this module. :)

Thanks!

**Comment by chantastic** [comment]
Hi @mxmtsk!

Thanks for creating this issue.
I just totally forgot to add a license file.
Added it back in August — after you filed this — and forgot to reply.
(obviously I'm real good at this open source thing 😅)

License was added [here](https://github.com/chantastic/react-svg-spinner/commit/0f6b5972228840bfa8d1b4741c1b95d3a77e8514).
Hope that helps.

Thanks!

Michael

**Comment by chantastic** [comment]
References: https://github.com/chantastic/react-svg-spinner/commit/0f6b5972228840bfa8d1b4741c1b95d3a77e8514
